//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod pms_attr;
pub mod pms_attr_attrgroup_relation;
pub mod pms_attr_group;
pub mod pms_brand;
pub mod pms_category;
pub mod pms_category_brand_relation;
pub mod pms_comment_replay;
pub mod pms_product_attr_value;
pub mod pms_sku_images;
pub mod pms_sku_info;
pub mod pms_sku_sale_attr_value;
pub mod pms_spu_comment;
pub mod pms_spu_images;
pub mod pms_spu_info;
pub mod pms_spu_info_desc;
