//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "pms_spu_info_desc")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub spu_id: i64,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")", nullable)]
    pub decript: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
