//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "pms_spu_comment")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub sku_id: Option<i64>,
    pub spu_id: Option<i64>,
    pub spu_name: Option<String>,
    pub member_nick_name: Option<String>,
    pub star: Option<i8>,
    pub member_ip: Option<String>,
    pub create_time: Option<DateTime>,
    pub show_status: Option<i8>,
    pub spu_attributes: Option<String>,
    pub likes_count: Option<i32>,
    pub reply_count: Option<i32>,
    pub resources: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    pub member_icon: Option<String>,
    pub comment_type: Option<i8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
