//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "pms_sku_info")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub sku_id: i64,
    pub spu_id: Option<i64>,
    pub sku_name: Option<String>,
    pub sku_desc: Option<String>,
    pub catalog_id: Option<i64>,
    pub brand_id: Option<i64>,
    pub sku_default_img: Option<String>,
    pub sku_title: Option<String>,
    pub sku_subtitle: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((18, 4)))", nullable)]
    pub price: Option<Decimal>,
    pub sale_count: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
