//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "pms_category_brand_relation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub brand_id: Option<i64>,
    pub catelog_id: Option<i64>,
    pub brand_name: Option<String>,
    pub catelog_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
