//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "pms_product_attr_value")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub spu_id: Option<i64>,
    pub attr_id: Option<i64>,
    pub attr_name: Option<String>,
    pub attr_value: Option<String>,
    pub attr_sort: Option<i32>,
    pub quick_show: Option<i8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
