//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "pms_attr")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub attr_id: i64,
    pub attr_name: Option<String>,
    pub search_type: Option<i8>,
    pub value_type: Option<i8>,
    pub icon: Option<String>,
    pub value_select: Option<String>,
    pub attr_type: Option<i8>,
    pub enable: Option<i64>,
    pub catelog_id: Option<i64>,
    pub show_desc: Option<i8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
