//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "pms_attr_attrgroup_relation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub attr_id: Option<i64>,
    pub attr_group_id: Option<i64>,
    pub attr_sort: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
