//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Serialize,Deserialize};
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq,Serialize,Deserialize)]
#[sea_orm(table_name = "pms_category")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub cat_id: i64,
    pub name: Option<String>,
    pub parent_cid: Option<i64>,
    pub cat_level: Option<i32>,
    pub show_status: Option<i8>,
    pub sort: Option<i32>,
    pub icon: Option<String>,
    pub product_unit: Option<String>,
    pub product_count: Option<i32>,
    #[sea_orm(ignore)]
    #[serde(skip_deserializing)]
    pub children : Vec<Model>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
