//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::pms_attr::Entity as PmsAttr;
pub use super::pms_attr_attrgroup_relation::Entity as PmsAttrAttrgroupRelation;
pub use super::pms_attr_group::Entity as PmsAttrGroup;
pub use super::pms_brand::Entity as PmsBrand;
pub use super::pms_category::Entity as PmsCategory;
pub use super::pms_category_brand_relation::Entity as PmsCategoryBrandRelation;
pub use super::pms_comment_replay::Entity as PmsCommentReplay;
pub use super::pms_product_attr_value::Entity as PmsProductAttrValue;
pub use super::pms_sku_images::Entity as PmsSkuImages;
pub use super::pms_sku_info::Entity as PmsSkuInfo;
pub use super::pms_sku_sale_attr_value::Entity as PmsSkuSaleAttrValue;
pub use super::pms_spu_comment::Entity as PmsSpuComment;
pub use super::pms_spu_images::Entity as PmsSpuImages;
pub use super::pms_spu_info::Entity as PmsSpuInfo;
pub use super::pms_spu_info_desc::Entity as PmsSpuInfoDesc;
